// Code generated by clop-gen; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"github.com/BurntSushi/toml"
	"gopkg.in/yaml.v3"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Options的Parse方法，用于解析命令行参数
func (c *Options) Parse(args []string) error {
	if len(args) == 0 {
		args = os.Args[1:]
	}

	// 设置默认值
	if val, err := strconv.ParseFloat("3.14159265359", 64); err == nil {
		c.Float64 = val
	}
	if val, err := strconv.ParseFloat("2.7182818284", 64); err == nil {
		c.Float64Ptr = &val
	}
	for _, s := range strings.Split("1.1,2.2,3.3", ",") {
		if val, err := strconv.ParseFloat(s, 64); err == nil {
			c.Float64Slice = append(c.Float64Slice, val)
		}
	}

	// 检查是否指定了配置文件
	var configFile string
	for i := 0; i < len(args); i++ {
		if args[i] == "--config" || args[i] == "-c" {
			if i+1 < len(args) {
				configFile = args[i+1]
				// 移除 --config 和它的值，避免后续解析错误
				if i+2 < len(args) {
					args = append(args[:i], args[i+2:]...)
				} else {
					args = args[:i]
				}
				i--
				break
			}
		}
	}

	// 从配置文件加载选项
	if configFile != "" {
		if err := c.loadFromConfigFile(configFile); err != nil {
			return fmt.Errorf("加载配置文件失败: %w", err)
		}
	}

	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch {
		case arg == "--help" || arg == "-h":
			c.Usage()
			os.Exit(0)

		case arg == "-f" || arg == "--float64":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -f or --float64")
			}

			val, err := strconv.ParseFloat(args[i+1], 64)
			if err != nil {
				return fmt.Errorf("invalid value for -f or --float64: %v", err)
			}
			c.Float64 = val

			i++

		case arg == "--float64-ptr":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for --float64-ptr")
			}

			val, err := strconv.ParseFloat(args[i+1], 64)
			if err != nil {
				return fmt.Errorf("invalid value for --float64-ptr: %v", err)
			}
			c.Float64Ptr = &val

			i++

		case arg == "--float64-slice":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for --float64-slice")
			}

			for _, s := range strings.Split(args[i+1], ",") {
				if val, err := strconv.ParseFloat(s, 64); err == nil {
					c.Float64Slice = append(c.Float64Slice, val)
				}
			}

			i++

		case arg == "--float64-slice-ptr":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for --float64-slice-ptr")
			}

			i++

		case arg == "-h" || arg == "--help":

			c.Help = true

		default:
			return fmt.Errorf("unknown option: %s", arg)
		}
	}

	return nil
}

// UsageTmpl 是用于生成 Usage 函数的模板
func (c *Options) Usage() {
	fmt.Println(`USAGE:
  myapp [OPTIONS]

OPTIONS:
    -c, --config    指定配置文件路径 (支持 JSON, YAML, TOML)
    -h, --help      显示帮助信息
    -f, --float64    A float64 value (default: 3.14159265359)
    --float64-ptr    A float64 pointer value (default: 2.7182818284)
    --float64-slice    A slice of float64 values (default: 1.1,2.2,3.3)
    --float64-slice-ptr    A pointer to a slice of float64 values (default: 4.4,5.5,6.6)
    -h, --help    Show help information
`)
}

func (c *Options) loadFromConfigFile(configFile string) error {
	data, err := os.ReadFile(configFile)
	if err != nil {
		return fmt.Errorf("读取配置文件失败: %w", err)
	}

	// 根据文件扩展名选择解析方式
	ext := filepath.Ext(configFile)
	switch strings.ToLower(ext) {
	case ".json":
		return json.Unmarshal(data, c)
	case ".yaml", ".yml":
		return yaml.Unmarshal(data, c)
	case ".toml":
		_, err := toml.Decode(string(data), c)
		return err
	default:
		return fmt.Errorf("不支持的配置文件格式: %s", ext)
	}
}
