// Code generated by clop-gen; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"github.com/BurntSushi/toml"
	"gopkg.in/yaml.v3"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Options的Parse方法，用于解析命令行参数
func (c *Options) Parse(args []string) error {
	if len(args) == 0 {
		args = os.Args[1:]
	}

	// 设置默认值
	if u, err := url.Parse("https://github.com/antlabs/quickclop"); err == nil {
		c.Website = *u
	}

	// 从环境变量中读取值

	if envVal := os.Getenv("API_URL"); envVal != "" {

		if u, err := url.Parse(envVal); err == nil {
			c.ApiURL = u
		}

	}

	// 检查是否指定了配置文件
	var configFile string
	for i := 0; i < len(args); i++ {
		if args[i] == "--config" || args[i] == "-c" {
			if i+1 < len(args) {
				configFile = args[i+1]
				// 移除 --config 和它的值，避免后续解析错误
				if i+2 < len(args) {
					args = append(args[:i], args[i+2:]...)
				} else {
					args = args[:i]
				}
				i--
				break
			}
		}
	}

	// 从配置文件加载选项
	if configFile != "" {
		if err := c.loadFromConfigFile(configFile); err != nil {
			return fmt.Errorf("加载配置文件失败: %w", err)
		}
	}

	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch {
		case arg == "--help" || arg == "-h":
			c.Usage()
			os.Exit(0)

		case arg == "-n" || arg == "--name":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -n or --name")
			}

			c.Name = args[i+1]

			i++

		case arg == "-a" || arg == "--age":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -a or --age")
			}

			val, err := strconv.Atoi(args[i+1])
			if err != nil {
				return fmt.Errorf("invalid value for -a or --age: %v", err)
			}
			c.Age = val

			i++

		case arg == "-w" || arg == "--website":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -w or --website")
			}

			if u, err := url.Parse(args[i+1]); err == nil {
				c.Website = *u
			}

			i++

		case arg == "--api":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for --api")
			}

			if u, err := url.Parse(args[i+1]); err == nil {
				c.ApiURL = u
			}

			i++

		default:
			return fmt.Errorf("unknown option: %s", arg)
		}
	}

	return nil
}

// UsageTmpl 是用于生成 Usage 函数的模板
func (c *Options) Usage() {
	fmt.Println(`USAGE:
  myapp [OPTIONS]

OPTIONS:
    -c, --config    指定配置文件路径 (支持 JSON, YAML, TOML)
    -h, --help      显示帮助信息
    -n, --name    名称
    -a, --age    年龄
    -w, --website    网站 (default: https://github.com/antlabs/quickclop)
    --api    API地址 [env: API_URL]
`)
}

func (c *Options) loadFromConfigFile(configFile string) error {
	data, err := os.ReadFile(configFile)
	if err != nil {
		return fmt.Errorf("读取配置文件失败: %w", err)
	}

	// 根据文件扩展名选择解析方式
	ext := filepath.Ext(configFile)
	switch strings.ToLower(ext) {
	case ".json":
		return json.Unmarshal(data, c)
	case ".yaml", ".yml":
		return yaml.Unmarshal(data, c)
	case ".toml":
		_, err := toml.Decode(string(data), c)
		return err
	default:
		return fmt.Errorf("不支持的配置文件格式: %s", ext)
	}
}
