// Code generated by clop-gen; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"github.com/BurntSushi/toml"
	"gopkg.in/yaml.v3"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Config的Parse方法，用于解析命令行参数
func (c *Config) Parse(args []string) error {
	if len(args) == 0 {
		args = os.Args[1:]
	}

	// 设置默认值
	if val, err := strconv.ParseBool("false"); err == nil {
		c.Debug = val
	}
	if val, err := strconv.Atoi("8080"); err == nil {
		c.Port = val
	}
	c.Host = "localhost"
	c.LogLevel = "info"
	if val, err := strconv.Atoi("30"); err == nil {
		c.Timeout = val
	}
	c.DataDir = "./data"

	// 从环境变量中读取值

	if envVal := os.Getenv("APP_TIMEOUT"); envVal != "" {

		if val, err := strconv.Atoi(envVal); err == nil {
			c.Timeout = val
		}

	}

	// 检查是否指定了配置文件
	var configFile string
	for i := 0; i < len(args); i++ {
		if args[i] == "--config" || args[i] == "-c" {
			if i+1 < len(args) {
				configFile = args[i+1]
				// 移除 --config 和它的值，避免后续解析错误
				if i+2 < len(args) {
					args = append(args[:i], args[i+2:]...)
				} else {
					args = args[:i]
				}
				i--
				break
			}
		}
	}

	// 从配置文件加载选项
	if configFile != "" {
		if err := c.loadFromConfigFile(configFile); err != nil {
			return fmt.Errorf("加载配置文件失败: %w", err)
		}
	}

	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch {
		case arg == "--help" || arg == "-h":
			c.Usage()
			os.Exit(0)

		case arg == "-d" || arg == "--debug":

			c.Debug = true

		case arg == "-p" || arg == "--port":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -p or --port")
			}

			val, err := strconv.Atoi(args[i+1])
			if err != nil {
				return fmt.Errorf("invalid value for -p or --port: %v", err)
			}
			c.Port = val

			i++

		case arg == "-h" || arg == "--host":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -h or --host")
			}

			c.Host = args[i+1]

			i++

		case arg == "--log-level":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for --log-level")
			}

			c.LogLevel = args[i+1]

			i++

		case arg == "-t" || arg == "--timeout":

			if i+1 >= len(args) {
				return fmt.Errorf("missing value for -t or --timeout")
			}

			val, err := strconv.Atoi(args[i+1])
			if err != nil {
				return fmt.Errorf("invalid value for -t or --timeout: %v", err)
			}
			c.Timeout = val

			i++

		case !strings.HasPrefix(arg, "-"):

			c.DataDir = arg

		default:
			return fmt.Errorf("unknown option: %s", arg)
		}
	}

	return nil
}

// UsageTmpl 是用于生成 Usage 函数的模板
func (c *Config) Usage() {
	fmt.Println(`USAGE:
  myapp [OPTIONS] [ARGS]

OPTIONS:
    -c, --config    指定配置文件路径 (支持 JSON, YAML, TOML)
    -h, --help      显示帮助信息
    -d, --debug    启用调试模式 (default: false)
    -p, --port    服务端口 (default: 8080)
    -h, --host    服务主机 (default: localhost)
    --log-level    日志级别 (default: info)
    -t, --timeout    超时时间（秒） [env: APP_TIMEOUT] (default: 30)

ARGS:
    data-dir    数据目录 (default: ./data)
`)
}

func (c *Config) loadFromConfigFile(configFile string) error {
	data, err := os.ReadFile(configFile)
	if err != nil {
		return fmt.Errorf("读取配置文件失败: %w", err)
	}

	// 根据文件扩展名选择解析方式
	ext := filepath.Ext(configFile)
	switch strings.ToLower(ext) {
	case ".json":
		return json.Unmarshal(data, c)
	case ".yaml", ".yml":
		return yaml.Unmarshal(data, c)
	case ".toml":
		_, err := toml.Decode(string(data), c)
		return err
	default:
		return fmt.Errorf("不支持的配置文件格式: %s", ext)
	}
}
